##
## EPITECH PROJECT, 2019
## AIA_gomoku_2019
## File description:
## Makefile
##

NAME = pbrain-gomoku-ai

all:
	@ln -s src/pbrain_gomoku_ai.py ./$(NAME)
	@chmod +x $(NAME)

clean:
	@rm -rdf src/__pycache__

fclean: clean
	@rm -rdf $(NAME)

re: fclean all