##
## EPITECH PROJECT, 2019
## SEC_crypto_2019
## File description:
## Makefile
##

all:
	@cp src/challenge01.py ./challenge01
	@cp src/challenge02.py ./challenge02
	@cp src/challenge03.py ./challenge03
	@cp src/challenge04.py ./challenge04
	@cp src/challenge05.py ./challenge05
	@cp src/challenge06.py ./challenge06
	@cp src/challenge07.py ./challenge07
	@cp src/challenge08.py ./challenge08
	@cp src/tools01.py .
	@cp src/tools02.py .
	@chmod +x ./challenge01
	@chmod +x ./challenge02
	@chmod +x ./challenge03
	@chmod +x ./challenge04
	@chmod +x ./challenge05
	@chmod +x ./challenge06
	@chmod +x ./challenge07
	@chmod +x ./challenge08

clean:
	@rm -f ./challenge01
	@rm -f ./challenge02
	@rm -f ./challenge03
	@rm -f ./challenge04
	@rm -f ./challenge05
	@rm -f ./challenge06
	@rm -f ./challenge07
	@rm -f ./challenge08
	@rm -f ./tools01.py
	@rm -f ./tools02.py
	@rm -rdf ./__pycache__

fclean:	clean

re:	fclean all

.PHONY: all clean fclean re