name:                evalexpr
version:             0.1.0.0
github:              "githubuser/evalexpr"
license:             BSD3
author:              "Judicael DAMOUR & Nicolas AH-LEUNG"
maintainer:          "nicolas.ah-leung@epitech.eu & nicolas.ah-leung@epitech.eu"
copyright:           "2019 Judicael DAMOUR & Nicolas AH-LEUNG"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/evalexpr#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  evalexpr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evalexpr

tests:
  evalexpr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evalexpr
