version: '3'

services:
  poll:
    build: ./poll
    container_name: poll
    restart: always
    environment:
      - OPTION_A:"Ansible"
      - OPTION_B:"Chef"
      - OPTION_C:"Puppet"
      - OPTION_HOST:"redis"
    ports:
      - "5000:80"
    networks:
      - poll-tier
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
  db:
    image: postgres
    container_name: db
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'password'
      - POSTGRES_DB:'db-data'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier
      - result-tier
  result:
    build: ./result
    container_name: result
    restart: always
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'password'
    ports:
      - "5001:80"
    networks:
      - result-tier
  worker:
    build: ./worker
    container_name: worker
    restart: always
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'password'
    networks:
      - back-tier

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: