apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: default
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      restartPolicy: Always
      containers:
      - name: worker
        image: epitechcontent/t-dop-600-worker:k8s
        imagePullPolicy: "IfNotPresent"
        envFrom:
          - configMapRef:
              name: redis-config
          - configMapRef:
              name: postgres-config
          - secretRef:
              name: postgres-secret
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
